### ISSUE TITLE
Loading aborted due to error reloading workflow data

### ISSUE THREAD

**Issue by sandrosem** [ssitu/ComfyUI_NestedNodeBuilder#11]
I'm getting the following error when loading a workflow that's using nestednodebuilder:

Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of null (reading 'type')
TypeError: Cannot read properties of null (reading 'type')
    at ComfyNode.inheritPrimitiveWidgets (http://XXXXXX/extensions/ComfyUI_NestedNodeBuilder/nestedNode.js:187:26)
    at ComfyNode.nestedNodeSetup (http://XXXXXX/extensions/ComfyUI_NestedNodeBuilder/nestedNode.js:85:14)
    at ComfyNode.onAdded (http://XXXXXX/extensions/ComfyUI_NestedNodeBuilder/nestedNode.js:125:18)
    at nodeType.onAdded (http://XXXXXX/extensions/tinyterraNodes/ttNwidgets.js:392:49)
    at LGraph.add (http://XXXXXX/lib/litegraph.core.js:1453:18)
    at LGraph.configure (http://XXXXXX/lib/litegraph.core.js:2232:22)
    at LGraph.configure (http://XXXXXX/extensions/pysssss/CustomScripts/reroutePrimitive.js:14:29)
    at LGraph.configure (http://XXXXXX/extensions/pysssss/CustomScripts/snapToGrid.js:53:21)
    at ComfyApp.loadGraphData (http://XXXXXX/scripts/app.js:1227:15)
    at reader.onload (http://XXXXXX8/scripts/app.js:1535:10)
This may be due to the following script:
/extensions/ComfyUI_NestedNodeBuilder/nestedNode.js

Any idea what caused this and how to fix it?

**Comment by ssitu** [comment]
You are probably missing a custom node that’s used in a nested node. You’ll have to look through the .json of the workflow to find the missing nodes while I work on a fix.
