### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by mysteriousHerb** [ssitu/ComfyUI_NestedNodeBuilder#18]
TypeError: Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at ComfyNode.inheritPrimitiveWidgets (http://127.0.0.1:8188/extensions/ComfyUI_NestedNodeBuilder/nestedNode.js:386:58)
    at ComfyNode.nestedNodeSetup (http://127.0.0.1:8188/extensions/ComfyUI_NestedNodeBuilder/nestedNode.js:107:14)
    at ComfyNode.onAdded (http://127.0.0.1:8188/extensions/ComfyUI_NestedNodeBuilder/nestedNode.js:142:18)
    at LGraph.add (http://127.0.0.1:8188/lib/litegraph.core.js:1453:18)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2232:22)
    at LGraph.configure (http://127.0.0.1:8188/scripts/app.js:1191:22)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:53:21)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1441:15)
    at Rgthree.app.loadGraphData (http://127.0.0.1:8188/extensions/rgthree-comfy/rgthree.js:195:44)
This may be due to the following script:
/extensions/ComfyUI_NestedNodeBuilder/nestedNode.js

**Comment by ssitu** [comment]
Are you able to share a workflow with the problem?
